name: Build and Deploy
on:
  push:
    branches:
      - main
      - beta
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          TARGET_REPO: Degray84/figma-detoks
          TARGET_BRANCH: beta
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist
