name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          TARGET_REPO: Degray84/figma-detoks
          TARGET_BRANCH: main
          BUILD_SCRIPT: npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
